### ISSUE TITLE
Example docker-compose.yml 

### ISSUE THREAD

**Issue by Leopere** [cmars/onionpipe#11]
Dunno if you'd find this useful anywhere in your documentation but this works for me.
```yaml
version: "3.7"
services:
  oniongrok:
    image: ghcr.io/cmars/oniongrok:main
    ## You will need to consider changing the command.
    command: "--secrets /data/.local/share/oniongrok/secrets.json sign:80~80@sign"
    volumes:
      - ./data/:/data/.local/share/oniongrok/

## Demo App, Could be anything.
  sign:
    image: 'eerotal/libresignage:latest'
    volumes:
      - ./data/sign:/var/www/html/data'
```

At some point, I think it might not be a horrible idea to potentially look at making one of these examples that use the Traefik reverse proxy for fun and research.  Especially if that example just uses docker labels.
